// @generated by scripts/gen-card-schema.py from a2a.proto at
// a2aproject/A2A@72b3761bd84c59291da694dcd97cdfc2c010df39. Do not edit by hand.

use crate::schema_types::{Field, Kind, Presence, Shape};

/// Messages reachable from `AgentCard`, with their fields.
pub(crate) const MESSAGES: &[(&str, &[Field])] = &[
    ("AgentCard", &[
            Field { name: "name", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "description", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "supportedInterfaces", presence: Presence::Required, shape: Shape::Repeated, kind: Kind::Message("AgentInterface") },
            Field { name: "provider", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Message("AgentProvider") },
            Field { name: "version", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "documentationUrl", presence: Presence::Optional, shape: Shape::Single, kind: Kind::Str },
            Field { name: "capabilities", presence: Presence::Required, shape: Shape::Single, kind: Kind::Message("AgentCapabilities") },
            Field { name: "securitySchemes", presence: Presence::Implicit, shape: Shape::Map, kind: Kind::Message("SecurityScheme") },
            Field { name: "securityRequirements", presence: Presence::Implicit, shape: Shape::Repeated, kind: Kind::Message("SecurityRequirement") },
            Field { name: "defaultInputModes", presence: Presence::Required, shape: Shape::Repeated, kind: Kind::Str },
            Field { name: "defaultOutputModes", presence: Presence::Required, shape: Shape::Repeated, kind: Kind::Str },
            Field { name: "skills", presence: Presence::Required, shape: Shape::Repeated, kind: Kind::Message("AgentSkill") },
            Field { name: "signatures", presence: Presence::Implicit, shape: Shape::Repeated, kind: Kind::Message("AgentCardSignature") },
            Field { name: "iconUrl", presence: Presence::Optional, shape: Shape::Single, kind: Kind::Str },
    ]),
    ("AgentInterface", &[
            Field { name: "url", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "protocolBinding", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "tenant", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
            Field { name: "protocolVersion", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
    ]),
    ("AgentProvider", &[
            Field { name: "url", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "organization", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
    ]),
    ("AgentCapabilities", &[
            Field { name: "streaming", presence: Presence::Optional, shape: Shape::Single, kind: Kind::Bool },
            Field { name: "pushNotifications", presence: Presence::Optional, shape: Shape::Single, kind: Kind::Bool },
            Field { name: "extensions", presence: Presence::Implicit, shape: Shape::Repeated, kind: Kind::Message("AgentExtension") },
            Field { name: "extendedAgentCard", presence: Presence::Optional, shape: Shape::Single, kind: Kind::Bool },
    ]),
    ("SecurityScheme", &[
            Field { name: "apiKeySecurityScheme", presence: Presence::Oneof, shape: Shape::Single, kind: Kind::Message("APIKeySecurityScheme") },
            Field { name: "httpAuthSecurityScheme", presence: Presence::Oneof, shape: Shape::Single, kind: Kind::Message("HTTPAuthSecurityScheme") },
            Field { name: "oauth2SecurityScheme", presence: Presence::Oneof, shape: Shape::Single, kind: Kind::Message("OAuth2SecurityScheme") },
            Field { name: "openIdConnectSecurityScheme", presence: Presence::Oneof, shape: Shape::Single, kind: Kind::Message("OpenIdConnectSecurityScheme") },
            Field { name: "mtlsSecurityScheme", presence: Presence::Oneof, shape: Shape::Single, kind: Kind::Message("MutualTlsSecurityScheme") },
    ]),
    ("SecurityRequirement", &[
            Field { name: "schemes", presence: Presence::Implicit, shape: Shape::Map, kind: Kind::Message("StringList") },
    ]),
    ("AgentSkill", &[
            Field { name: "id", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "name", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "description", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "tags", presence: Presence::Required, shape: Shape::Repeated, kind: Kind::Str },
            Field { name: "examples", presence: Presence::Implicit, shape: Shape::Repeated, kind: Kind::Str },
            Field { name: "inputModes", presence: Presence::Implicit, shape: Shape::Repeated, kind: Kind::Str },
            Field { name: "outputModes", presence: Presence::Implicit, shape: Shape::Repeated, kind: Kind::Str },
            Field { name: "securityRequirements", presence: Presence::Implicit, shape: Shape::Repeated, kind: Kind::Message("SecurityRequirement") },
    ]),
    ("AgentCardSignature", &[
            Field { name: "protected", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "signature", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "header", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Struct },
    ]),
    ("AgentExtension", &[
            Field { name: "uri", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
            Field { name: "description", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
            Field { name: "required", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Bool },
            Field { name: "params", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Struct },
    ]),
    ("APIKeySecurityScheme", &[
            Field { name: "description", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
            Field { name: "location", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "name", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
    ]),
    ("HTTPAuthSecurityScheme", &[
            Field { name: "description", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
            Field { name: "scheme", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "bearerFormat", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
    ]),
    ("OAuth2SecurityScheme", &[
            Field { name: "description", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
            Field { name: "flows", presence: Presence::Required, shape: Shape::Single, kind: Kind::Message("OAuthFlows") },
            Field { name: "oauth2MetadataUrl", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
    ]),
    ("OpenIdConnectSecurityScheme", &[
            Field { name: "description", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
            Field { name: "openIdConnectUrl", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
    ]),
    ("MutualTlsSecurityScheme", &[
            Field { name: "description", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
    ]),
    ("StringList", &[
            Field { name: "list", presence: Presence::Implicit, shape: Shape::Repeated, kind: Kind::Str },
    ]),
    ("OAuthFlows", &[
            Field { name: "authorizationCode", presence: Presence::Oneof, shape: Shape::Single, kind: Kind::Message("AuthorizationCodeOAuthFlow") },
            Field { name: "clientCredentials", presence: Presence::Oneof, shape: Shape::Single, kind: Kind::Message("ClientCredentialsOAuthFlow") },
            Field { name: "implicit", presence: Presence::Oneof, shape: Shape::Single, kind: Kind::Message("ImplicitOAuthFlow") },
            Field { name: "password", presence: Presence::Oneof, shape: Shape::Single, kind: Kind::Message("PasswordOAuthFlow") },
            Field { name: "deviceCode", presence: Presence::Oneof, shape: Shape::Single, kind: Kind::Message("DeviceCodeOAuthFlow") },
    ]),
    ("AuthorizationCodeOAuthFlow", &[
            Field { name: "authorizationUrl", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "tokenUrl", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "refreshUrl", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
            Field { name: "scopes", presence: Presence::Required, shape: Shape::Map, kind: Kind::Str },
            Field { name: "pkceRequired", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Bool },
    ]),
    ("ClientCredentialsOAuthFlow", &[
            Field { name: "tokenUrl", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "refreshUrl", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
            Field { name: "scopes", presence: Presence::Required, shape: Shape::Map, kind: Kind::Str },
    ]),
    ("ImplicitOAuthFlow", &[
            Field { name: "authorizationUrl", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
            Field { name: "refreshUrl", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
            Field { name: "scopes", presence: Presence::Implicit, shape: Shape::Map, kind: Kind::Str },
    ]),
    ("PasswordOAuthFlow", &[
            Field { name: "tokenUrl", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
            Field { name: "refreshUrl", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
            Field { name: "scopes", presence: Presence::Implicit, shape: Shape::Map, kind: Kind::Str },
    ]),
    ("DeviceCodeOAuthFlow", &[
            Field { name: "deviceAuthorizationUrl", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "tokenUrl", presence: Presence::Required, shape: Shape::Single, kind: Kind::Str },
            Field { name: "refreshUrl", presence: Presence::Implicit, shape: Shape::Single, kind: Kind::Str },
            Field { name: "scopes", presence: Presence::Required, shape: Shape::Map, kind: Kind::Str },
    ]),
];
