#!/usr/bin/env python3
"""Generate the Agent Card field table used for A2A §8.4.1 default-value removal.

    python3 scripts/gen-card-schema.py <path/to/a2a.proto> <a2a git commit>

Reads the messages reachable from `AgentCard` and writes
crates/a2a-gov-card/src/schema.rs: for each field, its ProtoJSON name, whether
it's REQUIRED, `optional`, repeated, a map, part of a oneof, and its type.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCALARS = {"string", "bool", "bytes", "int32", "int64", "uint32", "uint64", "sint32", "sint64",
           "fixed32", "fixed64", "sfixed32", "sfixed64", "float", "double"}
FIELD = re.compile(r"^\s*(repeated |optional )?(map<[^>]+>|[\w.]+) (\w+) = \d+( \[[^\]]*\])?;", re.M)


def camel(snake: str) -> str:
    head, *rest = snake.split("_")
    return head + "".join(p[:1].upper() + p[1:] for p in rest)


def blocks(src: str, keyword: str) -> dict[str, str]:
    """Top-level `keyword Name { ... }` blocks, with nested braces balanced."""
    out = {}
    for m in re.finditer(rf"^{keyword} (\w+) \{{", src, re.M):
        depth, i = 1, m.end()
        while depth:
            depth += {"{": 1, "}": -1}.get(src[i], 0)
            i += 1
        out[m.group(1)] = src[m.end():i - 1]
    return out


def kind(type_name: str, messages: dict, enums: dict) -> str:
    base = type_name.split(".")[-1]
    if type_name == "google.protobuf.Struct":
        return "Kind::Struct"
    if type_name in SCALARS:
        return {"string": "Kind::Str", "bool": "Kind::Bool", "bytes": "Kind::Str"}.get(type_name, "Kind::Number")
    if base in enums:
        return "Kind::Enum"
    if base in messages:
        return f'Kind::Message("{base}")'
    raise SystemExit(f"unknown type {type_name}")


def main() -> None:
    proto_path, commit = sys.argv[1], sys.argv[2]
    src = re.sub(r"//[^\n]*", "", Path(proto_path).read_text())
    messages, enums = blocks(src, "message"), blocks(src, "enum")
    order, todo, seen = [], ["AgentCard"], set()
    while todo:
        name = todo.pop(0)
        if name in seen:
            continue
        seen.add(name)
        body = messages[name]
        oneof_bodies = "".join(re.findall(r"oneof \w+ \{(.*?)\}", body, re.S))
        fields = []
        for m in FIELD.finditer(body):
            label, typ, fname, opts = (m.group(1) or "").strip(), m.group(2), m.group(3), m.group(4) or ""
            is_map = typ.startswith("map<")
            value_type = typ[4:-1].split(",")[1].strip() if is_map else typ
            k = kind(value_type, messages, enums)
            if k.startswith("Kind::Message"):
                todo.append(value_type.split(".")[-1])
            presence = ("Presence::Required" if "REQUIRED" in opts else
                        "Presence::Optional" if label == "optional" else
                        "Presence::Oneof" if re.search(rf"\b{fname} = ", oneof_bodies) else
                        "Presence::Implicit")
            shape = "Shape::Map" if is_map else "Shape::Repeated" if label == "repeated" else "Shape::Single"
            fields.append(f'        Field {{ name: "{camel(fname)}", presence: {presence}, shape: {shape}, kind: {k} }},')
        order.append((name, fields))
    lines = [
        "// @generated by scripts/gen-card-schema.py from a2a.proto at",
        f"// a2aproject/A2A@{commit}. Do not edit by hand.",
        "",
        "use crate::schema_types::{Field, Kind, Presence, Shape};",
        "",
        "/// Messages reachable from `AgentCard`, with their fields.",
        "pub(crate) const MESSAGES: &[(&str, &[Field])] = &[",
    ]
    for name, fields in order:
        lines.append(f'    ("{name}", &[')
        lines.extend("    " + f for f in fields)
        lines.append("    ]),")
    lines.append("];")
    (ROOT / "crates/a2a-gov-card/src/schema.rs").write_text("\n".join(lines) + "\n")
    print(f"{len(order)} messages", file=sys.stderr)


if __name__ == "__main__":
    main()
